name: CI

# from https://github.com/atom/ci
on: [push, pull_request]

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v3
      with:
        version: ${{ matrix.channel }}
    - name: Install dependencies
      run: apm install
    - name: Run tests
      run: atom --test spec
